spring:
    config:
        activate:
            on-profile: dev
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        show-sql: true # true 설정시 JPA 쿼리문 확인 가능
        hibernate:
            ddl-auto: none # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
        properties:
            hibernate:
                format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
        open-in-view: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://j8c206.p.ssafy.io:3306/nogariDB?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        username: root #임시
        password: ssafy
    data:
        redis:
            host: nogari-redis
            port: 6379

server:
    port: 8080 # 서비스 포트
    servlet:
        context-path: /nogari
app:
    auth:
        kakao:
#            redirect-uri: http://localhost:8080/api/vi/oauth    # Token 받을 Uri 지정
            redirect-uri: http://localhost:3000/token/kakao     # Token 받을 Uri 지정

logging:
    level:
        web: INFO
        com: INFO
        root: iNFO

